// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdxhdahkospapbqjgrgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkeGhkYWhrb3NwYXBicWpncmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTI4MzAsImV4cCI6MjA2MzA2ODgzMH0.Bzh3vj6Um_HX4vV4MM3BK-xpcIetieF3usZYk61F890";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);